# Generated by Django 2.2.4 on 2019-08-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20190821_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='email',
            field=models.EmailField(default='a', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marker',
            name='marker_type',
            field=models.TextField(default='BORDER'),
            preserve_default=False,
        ),
    ]
