# Generated by Django 2.2.4 on 2019-11-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20190821_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
